version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.1
        environment:
          DJANGO_SETTINGS_MODULE: locallibrary.settings
          DATABASE_URL: postgres://root:circle_test@localhost:5432/circle_test
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: circle_test

    steps:
      - checkout

      - python/install-packages:
          pkg-manager: pip
          args: -r requirements.txt

      - run:
          name: Run Django tests and output to test-results
          command: |
            mkdir -p test-results
            python manage.py test --testrunner=xmlrunner.extra.djangotestrunner.XMLTestRunner --output-dir test-results

      - store_test_results:
          path: test-results

workflows:
  version: 2
  on_commit:
    jobs:
      - build_and_test
