version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.1
        environment:
          DJANGO_SETTINGS_MODULE: locallibrary.settings
          DATABASE_URL: postgres://root:circle_test@localhost:5432/circle_test
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: circle_test

        steps:
      - checkout

      - python/install-packages:
          pkg-manager: pipenv

      - python/load-cache

      - run:
          name: Migracje bazy danych
          command: |
            pipenv run python manage.py migrate

      - run:
          name: Uruchomienie testów i zapis do XML
          command: |
            mkdir -p test-results
            pipenv run python manage.py test --testrunner=xmlrunner.extra.djangotestrunner.XMLTestRunner --output-file=test-results/results.xml

      - store_test_results:
          path: test-results

      - python/save-cache


workflows:
  on_commit:
    jobs:
      - build_and_test

unittest-xml-reporting

