version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.1  # Zadanie 2
      - image: circleci/postgres:9.6.2  # Zadanie 3
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout  # Zadanie 4

      - python/install-packages:
          pkg-manager: pipenv  # Zadanie 4

      - run:  # Zadanie 5
          name: Run tests
          command: pipenv run python manage.py test  # lub python -m pytest – zależy od projektu

      - store_test_results:  # Zadanie 6
          path: test-results  # upewnij się, że testy zapisują wyniki tutaj, np. przez pytest z --junitxml

workflows:
  on_commit:
    jobs:
      - build_and_test