version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.1
        environment:
          DJANGO_SETTINGS_MODULE: locallibrary.settings
          DATABASE_URL: postgres://root:circle_test@localhost:5432/circle_test
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: circle_test

    steps:
      - checkout

      - run:
          name: Utworzenie i aktywacja środowiska wirtualnego + instalacja zależności
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Migracje bazy danych
          command: |
            . venv/bin/activate
            python manage.py migrate

      - run:
          name: Uruchomienie testów i zapis do test-reports/
          command: |
            . venv/bin/activate
            python -m xmlrunner discover -s . -o test-reports

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-results

      - persist_to_workspace:
          root: .
          paths:
            - test-results

workflows:
  on_commit:
    jobs:
      - build_and_test
